apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.deployment.secretRefName }}
  namespace: {{ .Values.namespace.name }}
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.deployment.secretRefName }}
    creationPolicy: Owner 
    deletionPolicy: Delete
  dataFrom:
  - extract:
      key: {{ .Values.deployment.secretRefName }}
