apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.role.metadata.name }}
  namespace: {{ .Values.namespace.name }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/log
  - persistentvolumeclaims
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
---