apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.roleBinding.metadata.name }}
  namespace: {{ .Values.namespace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.role.metadata.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceaccount.metadata.name }}
  namespace: {{ .Values.namespace.name }}
