apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceaccount.metadata.annotations.roleArn }}
    meta.helm.sh/release-namespace: {{ .Values.namespace.name }}
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: {{ .Release.Name }}
  name: {{ .Values.serviceaccount.metadata.name }}
  namespace: {{ .Values.namespace.name }}
