apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ .Values.keda.TriggerAuthentication.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: {{ .Values.deployment.secretRefName}}
      key: AZP_TOKEN
